name: Deploy to Railway

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Build application
        run: npm run build

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_NAME || 'veeqo-easypost-integration' }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Successfully deployed to Railway!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Deployment failed
        if: failure()
        run: |
          echo "❌ Deployment to Railway failed"
          echo "Please check the logs above for details"
